name: Renovate

on:
  schedule:
    - cron: '0/15 * * * *'

jobs:
  renovate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Self-hosted Renovate
        uses: renovatebot/github-action@v1.0.5
        with:
          token: ${{ secrets.RENOVATE_TOKEN }}
